[package]
name = "server-template"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1" }
soph = { version = "0.29.0", default-features = false }
soph-server = { version = "0.29.0", features = ["http1"] }
